#!/usr/bin/env python
"""Build the *real-data* group-recommendation explorer (self-contained HTML).

Dataset: MovieLens-100k (real titles + genres -> interpretable items & concepts).

The whole pipeline is built on the public ``grouprec`` API -- the point of the demo
is that obtaining the raw material is a few framework calls (see docs/EXPLORER.md):

    import grouprec as gr
    from grouprec import GroupRecommender
    from grouprec.backends import EASE
    from grouprec.aggregators import WeightedAverageAggregator, EPFuzzDAAggregator
    from grouprec.models import GroupIM

    data   = gr.datasets.load("ml-100k")                     # dataset processing
    groups = gr.groups.synthetic(data, kind="divergent", size=3, n=3, seed=0)  # group gen
    rec    = GroupRecommender(EASE(), WeightedAverageAggregator(member_weights=w))
    rec.fit(data); rec.recommend(members, k=5, candidates=cands)               # group rec

Everything shown is computed from these real components -- no mock/simulated matrices.
Provenance and every *subset* we display are documented in docs/demonstration.tex.

Honest notes:
* Group membership is generated by ``gr.groups.synthetic`` in three regimes -- SIMILAR,
  DIVERGENT and OUTLIER (3 each) -- and each group is tagged with its regime and the
  measured mean pairwise rating correlation.
* Group interactions are DERIVED (consensus items: rated >=4 by >=2 members), not simulated.
* Aggregators are the real library classes (``WeightedAverageAggregator``, ``EPFuzzDAAggregator``)
  run over a grid of normalised member weights; the slider snaps to the nearest grid point.
* The deep model is GroupIM (additive, attention-pooled -> cleanly steerable). AGREE is
  dropped (its non-linear head makes member steering weak). The influence weight is injected
  into GroupIM's own attention aggregator (alpha'_m ~ w_m * alpha_m), reducing to the native
  model at equal weights. This is NOT SAE steering.
* SAE concepts come from a Top-K SAE on GroupIM's item embeddings, each labelled by genre.

Usage:
    python scripts/build_explorer.py --out docs/group_rec_explorer.html
"""

from __future__ import annotations

import argparse
import itertools
import json
from collections import Counter
from pathlib import Path

import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F

import grouprec as gr
from grouprec.backends import EASE
from grouprec.models import GroupIM
from grouprec.aggregators import WeightedAverageAggregator, EPFuzzDAAggregator
from grouprec.aggregators._normalize import normalize_mgains

# ---- config --------------------------------------------------------------- #
GROUP_PLAN = [("similar", 3), ("divergent", 3), ("outlier", 3)]   # regime -> count
GROUP_SIZE = 3
N_CAND = 50                 # candidate pool per group (1 consensus positive + negatives)
LIKE = 4                    # rating >= LIKE counts as "liked"
CONSENSUS = 2               # item is a group positive if >= CONSENSUS members liked it
MIN_CONSENSUS_ITEMS = 3     # keep groups with at least this many consensus items
N_HISTORY = 3               # member history items shown (top by rating)
N_SAE_FEATS = 3             # SAE concepts shown per member
N_SAE_EXEMPLARS = 3         # exemplar films shown per concept
GRID_LEVELS = [0.0, 0.25, 0.5, 0.75, 1.0]     # per-member influence grid (5^3 = 125 combos)
SAE_HIDDEN, SAE_K, SAE_STEPS = 64, 6, 4000

MEMBER_STYLE = [
    {"color": "#5DCAA5", "bg": "#d0f0e4"},
    {"color": "#7F77DD", "bg": "#dddcf8"},
    {"color": "#D85A30", "bg": "#f7d8cc"},
]

ALGORITHMS = [
    {"key": "wAVG", "name": "Weighted average", "family": "AGG", "mode": "score",
     "desc": "Member-importance-weighted mean of members' real EASE scores (grouprec WeightedAverageAggregator). The influence weight tilts the mean."},
    {"key": "EPFuzzDA", "name": "EP-FuzzDA", "family": "AGG", "mode": "order",
     "desc": "Fairness aggregator (grouprec EPFuzzDAAggregator): greedily picks items to meet each member's target share. The influence weight sets each member's target importance."},
    {"key": "GroupIM", "name": "GroupIM", "family": "E2E", "mode": "score",
     "desc": "Deep model encoding each member's history, pooled by an attention aggregator; a learned predictor scores items. Influence reweights the aggregator (real forward pass)."},
]
SCORE_KEYS = [a["key"] for a in ALGORITHMS if a["mode"] == "score"]      # bar = 0..1 score
ORDER_KEYS = [a["key"] for a in ALGORITHMS if a["mode"] == "order"]      # bar = rank
E2E_KEYS = [a["key"] for a in ALGORITHMS if a["family"] == "E2E"]


def _minmax(v: np.ndarray) -> np.ndarray:
    lo, hi = float(v.min()), float(v.max())
    return (v - lo) / (hi - lo) if hi > lo else np.zeros_like(v)


def _norm_combo(levels):
    w = np.array(levels, dtype=float)
    s = w.sum()
    return (np.ones_like(w) / len(w)) if s == 0 else (w / s)


# --------------------------------------------------------------------------- #
# MovieLens metadata
# --------------------------------------------------------------------------- #
def load_movielens_metadata():
    base = Path.home() / "Library/Caches/grouprec/ml-100k/ml-100k"
    genres = [ln.split("|")[0] for ln in (base / "u.genre").read_text(encoding="latin-1").splitlines() if "|" in ln]
    titles, genre_vecs = {}, {}
    for line in (base / "u.item").read_text(encoding="latin-1").splitlines():
        if not line.strip():
            continue
        f = line.split("|")
        iid = int(f[0])
        titles[iid] = f[1]
        genre_vecs[iid] = np.array([int(x) for x in f[5:5 + len(genres)]], dtype=float)
    return genres, titles, genre_vecs


# --------------------------------------------------------------------------- #
# Top-K SAE (adapted from umap2026/sae.py TopKSAE)
# --------------------------------------------------------------------------- #
class TopKSAE(nn.Module):
    def __init__(self, input_dim, hidden, k, l1=1e-3):
        super().__init__()
        self.k, self.l1 = k, l1
        self.enc_w = nn.Parameter(nn.init.kaiming_uniform_(torch.empty(input_dim, hidden)))
        self.enc_b = nn.Parameter(torch.zeros(hidden))
        self.dec_w = nn.Parameter(nn.init.kaiming_uniform_(torch.empty(hidden, input_dim)))
        self.dec_b = nn.Parameter(torch.zeros(input_dim))
        self._normalize_decoder()

    @torch.no_grad()
    def _normalize_decoder(self):
        self.dec_w.data = self.dec_w.data / (self.dec_w.data.norm(dim=-1, keepdim=True) + 1e-8)

    def _standardize(self, x):
        return (x - x.mean(-1, keepdim=True)) / (x.std(-1, keepdim=True) + 1e-7)

    def encode(self, x):
        x = self._standardize(x)
        e = F.relu((x - self.dec_b) @ self.enc_w + self.enc_b)
        top = torch.topk(e, self.k, dim=-1)
        return torch.zeros_like(e).scatter(-1, top.indices, top.values)

    def forward(self, x):
        e = self.encode(x)
        return e @ self.dec_w + self.dec_b, e


def fit_topk_sae(item_emb, *, hidden=SAE_HIDDEN, k=SAE_K, steps=SAE_STEPS, seed=0):
    torch.manual_seed(seed)
    X = torch.as_tensor(item_emb, dtype=torch.float32)
    Xs = (X - X.mean(0)) / (X.std(0) + 1e-8)
    net = TopKSAE(Xs.shape[1], hidden, k)
    opt = torch.optim.Adam(net.parameters(), lr=1e-3)
    for _ in range(steps):
        recon, e = net(Xs)
        loss = (recon - net._standardize(Xs)).pow(2).mean() + net.l1 * e.abs().sum(-1).mean()
        opt.zero_grad(); loss.backward(); opt.step()
        net._normalize_decoder()
    with torch.no_grad():
        _, Z = net(Xs)
    return Z.numpy()


# --------------------------------------------------------------------------- #
# GroupIM: real weighted-aggregator forward pass (influence injected into pooling)
# --------------------------------------------------------------------------- #
def groupim_scores_w(model, midx, cidx, w):
    net = model.net_
    wt = torch.as_tensor(w, dtype=torch.float32)
    with torch.no_grad():
        vecs = model.M_[midx].unsqueeze(0)
        embeds = net.encoder(vecs)
        a = torch.tanh(net.aggregator.attention(embeds))
        wgt = torch.softmax(a, dim=1).squeeze(0).squeeze(-1)
        wgt = wgt * wt
        wgt = wgt / (wgt.sum() + 1e-12)
        g = (embeds.squeeze(0) * wgt[:, None]).sum(0, keepdim=True)
        logits = net.group_predictor(g).squeeze(0).cpu().numpy()
        att = np.repeat(wgt.cpu().numpy()[:, None], len(cidx), axis=1)
    return logits[cidx.cpu().numpy()], att


def build_groupim_grid(model, midx, cidx):
    grid, M = {}, len(midx)
    for combo in itertools.product(range(len(GRID_LEVELS)), repeat=M):
        w = [GRID_LEVELS[c] for c in combo]
        if sum(w) == 0:
            w = [1.0] * M
        s, _ = groupim_scores_w(model, midx, cidx, w)
        grid["".join(str(c) for c in combo)] = [round(float(x), 4) for x in _minmax(s)]
    _, att = groupim_scores_w(model, midx, cidx, [1.0] * M)
    return grid, att


# --------------------------------------------------------------------------- #
# Aggregator grids (real grouprec aggregator classes over the weight grid)
# --------------------------------------------------------------------------- #
def build_wavg_score_grid(rm):
    """Score grid for wAVG. We bake the weighted mean (for the 0-1 bar) AND assert it
    matches grouprec's WeightedAverageAggregator ordering -> genuine framework reuse."""
    grid, M, C = {}, rm.shape[0], rm.shape[1]
    for combo in itertools.product(range(len(GRID_LEVELS)), repeat=M):
        w = _norm_combo([GRID_LEVELS[c] for c in combo])
        scores = (w[:, None] * rm).sum(0)
        fw_order = WeightedAverageAggregator(member_weights=w).aggregate(rm, C)
        assert int(np.argsort(-scores, kind="stable")[0]) == int(fw_order[0]), "wAVG mismatch"
        grid["".join(str(c) for c in combo)] = [round(float(x), 4) for x in _minmax(scores)]
    return grid


def build_epfuzzda_order_grid(rm):
    grid, M, C = {}, rm.shape[0], rm.shape[1]
    for combo in itertools.product(range(len(GRID_LEVELS)), repeat=M):
        w = _norm_combo([GRID_LEVELS[c] for c in combo])
        order = EPFuzzDAAggregator(member_weights=w).aggregate(rm, C)
        grid["".join(str(c) for c in combo)] = [int(x) for x in order]
    return grid


# --------------------------------------------------------------------------- #
# main build
# --------------------------------------------------------------------------- #
def build(out: Path) -> None:
    genres, titles, genre_vecs = load_movielens_metadata()
    data = gr.datasets.load("ml-100k")
    ui, ii = data.user_index, data.item_index
    items_arr = data.items
    inter = data.interactions
    liked = {int(u): set(sub.loc[sub["rating"] >= LIKE, "item"].astype(int)) for u, sub in inter.groupby("user")}
    # SUBSET RULE (history): top-N_HISTORY items by rating, ties broken by ascending item id (deterministic).
    rated_top = {int(u): sub.sort_values(["rating", "item"], ascending=[False, True])["item"].astype(int).tolist()
                 for u, sub in inter.groupby("user")}
    R = data.user_item_matrix(value="rating")

    def consensus_items(mset):
        cnt = Counter()
        for m in mset:
            cnt.update(liked.get(m, ()))
        return [it for it, c in cnt.items() if c >= CONSENSUS]

    def cohesion(mset):
        rows = np.array([R[ui[m]] for m in mset], dtype=float)
        cors = [float(np.corrcoef(rows[a], rows[b])[0, 1])
                for a, b in itertools.combinations(range(len(mset)), 2)
                if rows[a].std() > 0 and rows[b].std() > 0]
        return float(np.mean(cors)) if cors else 0.0

    # ---- groups via the framework's synthetic sampler, one regime at a time ---- #
    print("[groups] generating via gr.groups.synthetic (similar / divergent / outlier) ...", flush=True)
    chosen, group_items, group_kinds = [], [], []
    for kind, n_want in GROUP_PLAN:
        kept, seen = 0, set()
        cand_groups = gr.groups.synthetic(data, kind=kind, size=GROUP_SIZE, n=max(60, n_want * 20), seed=0)
        for members in cand_groups:
            key = tuple(sorted(int(x) for x in members))
            if key in seen:
                continue
            seen.add(key)
            cons = consensus_items(key)
            if len(cons) >= MIN_CONSENSUS_ITEMS:
                chosen.append(list(key)); group_items.append(cons); group_kinds.append(kind)
                kept += 1
            if kept >= n_want:
                break
        print(f"  [{kind}] kept {kept}/{n_want}")
    cohesions = [cohesion(m) for m in chosen]

    groups = gr.Groups([np.array(m, dtype=np.int64) for m in chosen],
                       metadata={"kind": "synthetic", "source": "ml-100k"})
    group_interactions = {g: group_items[g] for g in range(len(chosen))}

    # ---- fit recommenders (framework) ---- #
    print("[fit] EASE ...", flush=True)
    ease = EASE(reg=200.0).fit(data)
    print("[fit] GroupIM ...", flush=True)
    groupim = GroupIM(groups, group_interactions, epochs=40, pretrain_epochs=10, seed=0).fit(data)

    # ---- SAE on GroupIM item embeddings (group_predictor rows), labelled by genre ---- #
    print("[fit] Top-K SAE on GroupIM item embeddings ...", flush=True)
    item_emb = groupim.net_.group_predictor.weight.detach().cpu().numpy()    # (n_items, d)
    Z = fit_topk_sae(item_emb)
    Gmat = np.array([genre_vecs.get(int(items_arr[idx]), np.zeros(len(genres))) for idx in range(len(items_arr))])

    def feature_label(f):
        # SUBSET RULE (exemplars): top-8 items by SAE activation (stable ties) -> genre label; show top-N_SAE_EXEMPLARS.
        top = np.argsort(-Z[:, f], kind="stable")[:8]
        gsum = Gmat[top].sum(0)
        items = [int(items_arr[t]) for t in top[:N_SAE_EXEMPLARS]]
        if gsum.sum() == 0:
            return "mixed", items
        names = [genres[j] for j in np.argsort(-gsum, kind="stable")[:2] if gsum[j] > 0]
        return " / ".join(names), items

    feat_cache = {f: feature_label(f) for f in range(Z.shape[1])}

    rng = np.random.default_rng(0)
    groups_out = []
    for gslot, mset in enumerate(chosen):
        cons = group_items[gslot]
        pos = int(cons[0])
        member_internal = torch.as_tensor([ui[m] for m in mset], dtype=torch.long)
        # SUBSET RULE (candidates): pos consensus item + uniformly-sampled negatives that no member rated (seed gslot).
        member_rated = set()
        for m in mset:
            member_rated.update(rated_top.get(m, ()))
        neg_pool = [int(items_arr[idx]) for idx in range(len(items_arr))
                    if int(items_arr[idx]) not in member_rated and int(items_arr[idx]) != pos]
        grng = np.random.default_rng(gslot)
        negs = list(grng.choice(neg_pool, size=min(N_CAND - 1, len(neg_pool)), replace=False))
        cand = [pos] + [int(x) for x in negs]
        cidx = torch.as_tensor([ii[c] for c in cand], dtype=torch.long)

        # per-member normalised scores via the framework normalizer (same as GroupRecommender)
        scores = np.asarray(ease.score(mset, items=cand), dtype=float)        # (M, C), framework EASE
        rm = normalize_mgains(scores, "minmax")                              # framework normalizer

        score_grid = {"wAVG": build_wavg_score_grid(rm),
                      "GroupIM": None}
        order_grid = {"EPFuzzDA": build_epfuzzda_order_grid(rm)}
        gim_grid, gim_att = build_groupim_grid(groupim, member_internal, cidx)
        score_grid["GroupIM"] = gim_grid

        members_out = []
        for mi, m in enumerate(mset):
            hist = [h for h in rated_top.get(m, []) if h in titles][:N_HISTORY]
            hidx = [ii[h] for h in rated_top.get(m, []) if h in ii]
            # SUBSET RULE (concepts): top-N_SAE_FEATS features by mean activation over the member's items (stable ties).
            top_feats = np.argsort(-Z[hidx].mean(0), kind="stable")[:N_SAE_FEATS].tolist() if hidx else [0, 1, 2]
            sae = [{"label": feat_cache[f][0], "items": feat_cache[f][1]} for f in top_feats]
            members_out.append({
                "uid": m, "label": f"User {m}", "initials": f"U{m}",
                "color": MEMBER_STYLE[mi]["color"], "bg": MEMBER_STYLE[mi]["bg"],
                "history": hist, "sae": sae,
            })

        kind = group_kinds[gslot]
        groups_out.append({
            "label": f"Group {gslot} ({kind}) · users {', '.join(str(m) for m in mset)}",
            "kind": kind, "cohesion": round(cohesions[gslot], 2),
            "members": members_out, "candidates": cand, "pos": pos,
            "agg": [r.round(4).tolist() for r in rm],            # per-member scores (attribution)
            "scoreGrid": score_grid,                              # wAVG + GroupIM: combo -> [C scores]
            "orderGrid": order_grid,                              # EPFuzzDA: combo -> [ordering]
            "att": {"GroupIM": [[round(float(x), 4) for x in row] for row in gim_att]},
        })
        print(f"  [group {gslot + 1}/{len(chosen)}] {kind} users={mset} coh={cohesions[gslot]:.2f} consensus={len(cons)}")

    payload = {
        "dataset": "MovieLens-100k",
        "algorithms": ALGORITHMS, "scoreKeys": SCORE_KEYS, "orderKeys": ORDER_KEYS, "e2eKeys": E2E_KEYS,
        "gridLevels": GRID_LEVELS,
        "titles": {str(it): titles.get(it, f"Item {it}")
                   for g in groups_out
                   for it in (g["candidates"]
                              + [x for mo in g["members"] for x in mo["history"]]
                              + [x for mo in g["members"] for f in mo["sae"] for x in f["items"]])},
        "groups": groups_out,
    }
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(render_html(payload))
    print(f"\nwrote {out}  ({len(groups_out)} groups, {len(ALGORITHMS)} algorithms, {out.stat().st_size/1e6:.2f} MB)")


def render_html(payload: dict) -> str:
    return _HTML_TEMPLATE.replace("/*__DATA__*/", json.dumps(payload, separators=(",", ":")))


_HTML_TEMPLATE = r"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Group Recommendation Explorer — MovieLens-100k</title>
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/4.4.1/chart.umd.min.js"></script>
<style>
  :root{--bg:#f8f7f3;--surface:#fff;--surface1:#f1efe8;--border:rgba(0,0,0,.12);
    --border-strong:rgba(0,0,0,.22);--text:#2c2c2a;--text-sec:#5f5e5a;--text-muted:#888780;
    --accent:#185FA5;--accent-bg:#E6F1FB;--agg:#2f8f5b;--agg-bg:#e2f4ea;--e2e:#7a52c9;--e2e-bg:#efe9fb;
    --bar:#7c8aa0;--pos:#c2891b;--radius:8px;}
  @media (prefers-color-scheme:dark){:root{--bg:#1e1e1c;--surface:#2c2c2a;--surface1:#242422;
    --border:rgba(255,255,255,.1);--border-strong:rgba(255,255,255,.18);--text:#e8e6dc;--text-sec:#b4b2a9;
    --text-muted:#6e6d67;--accent:#85B7EB;--accent-bg:#042C53;--agg:#69c993;--agg-bg:#10301f;--e2e:#b497ec;--e2e-bg:#241636;
    --bar:#8b97a8;--pos:#e0a93a;}}
  *{box-sizing:border-box;margin:0;padding:0}
  body{font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;background:var(--bg);color:var(--text);padding:24px;min-height:100vh}
  h1{font-size:17px;font-weight:600;margin-bottom:4px}
  .subtitle{font-size:12px;color:var(--text-muted);margin-bottom:18px}
  .controls{display:flex;gap:10px;flex-wrap:wrap;align-items:center;margin-bottom:16px}
  select{font-size:13px;padding:7px 10px;border-radius:var(--radius);border:.5px solid var(--border-strong);background:var(--surface);color:var(--text);min-width:200px}
  .badge{font-size:11px;font-weight:600;padding:3px 9px;border-radius:20px;letter-spacing:.04em}
  .badge.AGG{background:var(--agg-bg);color:var(--agg)}.badge.E2E{background:var(--e2e-bg);color:var(--e2e)}
  .badge.coh{background:var(--surface1);color:var(--text-sec);border:.5px solid var(--border)}
  .btn{font-size:12px;padding:6px 12px;border-radius:var(--radius);border:.5px solid var(--border-strong);background:var(--surface);color:var(--text-sec);cursor:pointer}
  .btn:hover{border-color:var(--accent);color:var(--accent)}
  .algo-desc{font-size:12px;color:var(--text-sec);background:var(--surface1);border:.5px solid var(--border);border-radius:var(--radius);padding:8px 11px;margin-bottom:16px;line-height:1.5}
  .grid{display:grid;grid-template-columns:1fr 1fr;gap:18px}
  @media (max-width:760px){.grid{grid-template-columns:1fr}}
  .section-label{font-size:11px;color:var(--text-muted);text-transform:uppercase;letter-spacing:.06em;margin-bottom:8px}
  .tab-row{display:flex;gap:4px;margin-bottom:10px;flex-wrap:wrap}
  .tab-btn{font-size:12px;padding:4px 10px;border-radius:var(--radius);border:.5px solid var(--border-strong);background:transparent;color:var(--text-sec);cursor:pointer}
  .tab-btn.active{background:var(--accent-bg);color:var(--accent);border-color:var(--accent)}
  .note-box{font-size:12px;color:var(--text-sec);background:var(--surface1);border-radius:var(--radius);padding:8px 10px;margin-bottom:10px;border:.5px solid var(--border);line-height:1.5}
  .user-card{background:var(--surface);border:.5px solid var(--border);border-radius:12px;padding:12px 14px;margin-bottom:8px}
  .user-header{display:flex;align-items:center;gap:10px;margin-bottom:8px}
  .avatar{width:34px;height:34px;border-radius:50%;display:flex;align-items:center;justify-content:center;font-size:11px;font-weight:600;flex-shrink:0}
  .slider-row{display:flex;align-items:center;gap:8px;font-size:12px;color:var(--text-sec)}
  .slider-row input[type=range]{flex:1;accent-color:var(--accent)}
  .slider-row .val{min-width:34px;text-align:right;color:var(--text)}
  .recs-card{background:var(--surface);border:.5px solid var(--border);border-radius:12px;padding:12px 14px}
  .rec-item{display:flex;align-items:center;gap:10px;padding:9px 0;border-bottom:.5px solid var(--border)}
  .rec-item:last-child{border-bottom:none}
  .rank-badge{width:22px;height:22px;border-radius:50%;background:var(--surface1);border:.5px solid var(--border-strong);display:flex;align-items:center;justify-content:center;font-size:11px;color:var(--text-muted);flex-shrink:0}
  .rec-name{flex:1;min-width:0}
  .rec-name .title{font-size:13px;font-weight:500;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}
  .rec-name .title .pos-tag{color:var(--pos);font-weight:600}
  .rec-name .genre{font-size:11px;color:var(--text-muted)}
  .scoreval{font-size:11px;color:var(--text-muted);min-width:30px;text-align:right;font-variant-numeric:tabular-nums}
  .bar-bg{width:54px;height:6px;background:var(--surface1);border-radius:3px;overflow:hidden}
  .bar-fill{height:100%;border-radius:3px;background:var(--bar);transition:width .35s ease}
  .dots{display:flex;gap:4px;align-items:center;width:46px;justify-content:flex-end}
  .dot{width:9px;height:9px;border-radius:50%;transition:transform .2s,opacity .2s;cursor:default}
  .attr-box{font-size:12px;color:var(--text-sec);background:var(--surface1);border-radius:var(--radius);padding:10px 11px;border:.5px solid var(--border);line-height:1.7}
  .attr-box b{color:var(--text)} .attr-box .mono{font-size:11px;color:var(--text-sec)}
  .attr-note{font-size:11px;color:var(--text-muted);margin-top:8px;line-height:1.45}
  .legend{display:flex;gap:12px;margin-top:10px;flex-wrap:wrap}
  .legend-item{display:flex;align-items:center;gap:5px;font-size:11px;color:var(--text-muted)}
  .legend-dot{width:10px;height:10px;border-radius:50%}
  .chart-wrap{margin-top:14px;background:var(--surface);border:.5px solid var(--border);border-radius:12px;padding:12px 14px}
  .tip{position:fixed;pointer-events:none;background:var(--text);color:var(--bg);font-size:11px;padding:4px 7px;border-radius:5px;opacity:0;transition:opacity .12s;z-index:10;white-space:nowrap}
</style>
</head>
<body>
<h1>Group recommendation explorer</h1>
<p class="subtitle">Real MovieLens-100k · groups from <code>gr.groups.synthetic</code> (similar / divergent / outlier) with consensus-derived interactions · the slider is each member's <b>importance weight</b> (normalised to sum to 100%)</p>

<div class="controls">
  <select id="algo-select" onchange="onAlgo()"></select>
  <span id="algo-badge" class="badge"></span>
  <select id="group-select" onchange="onGroup()"></select>
  <span id="coh-badge" class="badge coh"></span>
  <button class="btn" onclick="resetWeights()">Reset weights</button>
</div>
<div class="algo-desc" id="algo-desc"></div>

<div class="grid">
  <div>
    <p class="section-label">Group members</p>
    <div class="note-box" id="method-note"></div>
    <div id="users-container"></div>
    <div style="margin-top:14px">
      <p class="section-label">Attribution view</p>
      <div class="tab-row" id="attr-tabs">
        <button class="tab-btn active" data-v="history" onclick="setAttrView('history')">Item history</button>
        <button class="tab-btn" data-v="received" onclick="setAttrView('received')">Recs received</button>
        <button class="tab-btn" data-v="latent" onclick="setAttrView('latent')">Latent concepts</button>
      </div>
      <div class="attr-box" id="attr-detail"></div>
      <div class="attr-note" id="attr-note"></div>
    </div>
    <div class="legend" id="legend"></div>
  </div>
  <div>
    <p class="section-label">Group recommendations (top 5 of <span id="cand-n"></span> candidates)</p>
    <div class="recs-card" id="recs-container"></div>
    <p class="attr-note">Number = the item's group score (0–1) for score-based methods, or its rank for the selection-based fair aggregator · dots = each user's share of that item's relevance (hover for %) · <span style="color:var(--pos)">amber ✓</span> = a consensus item the group liked</p>
    <div class="chart-wrap">
      <p class="section-label">Aggregate user contribution across the top 5</p>
      <div style="position:relative;height:90px"><canvas id="contrib-chart"></canvas></div>
    </div>
  </div>
</div>
<div class="tip" id="tip"></div>

<script>
const DATA = /*__DATA__*/;
const ALGOS = DATA.algorithms, LEVELS = DATA.gridLevels, TITLES = DATA.titles;
const SCOREK = DATA.scoreKeys, ORDERK = DATA.orderKeys;
const tip = document.getElementById('tip');
let algoKey = ALGOS[0].key, groupIdx = 0, attrView = 'history', weights = [], chart = null;

function algo(){ return ALGOS.find(a => a.key === algoKey); }
function group(){ return DATA.groups[groupIdx]; }
function fam(){ return algo().family; }
function isE2E(){ return fam() === 'E2E'; }
function isOrder(){ return ORDERK.indexOf(algoKey) >= 0; }
function title(id){ return TITLES[id] || ('Item ' + id); }
function comboKey(){ return weights.map(w=>{let bi=0,bd=9;LEVELS.forEach((L,i)=>{const d=Math.abs(L-w);if(d<bd){bd=d;bi=i;}});return bi;}).join(''); }
function eqKey(){ return group().members.map(()=>{let bi=0,bd=9;LEVELS.forEach((L,i)=>{const d=Math.abs(L-0.5);if(d<bd){bd=d;bi=i;}});return bi;}).join(''); }

function initControls(){
  document.getElementById('algo-select').innerHTML = ALGOS.map(a=>`<option value="${a.key}">${a.name} [${a.family}]</option>`).join('');
  document.getElementById('group-select').innerHTML = DATA.groups.map((g,i)=>`<option value="${i}">${g.label}</option>`).join('');
}
function onAlgo(){ algoKey = document.getElementById('algo-select').value; renderAll(); }
function onGroup(){ groupIdx = +document.getElementById('group-select').value; resetWeights(); }
function resetWeights(){ weights = group().members.map(()=>0.5); renderAll(); }
function normWeights(){ const t = weights.reduce((a,b)=>a+b,0)||1; return weights.map(w=>w/t); }

function computeScores(){
  const g = group(), M = g.members.length, C = g.candidates.length, wn = normWeights();
  let score = new Array(C).fill(0);
  let contrib = Array.from({length:M},()=>new Array(C).fill(0));
  const S = g.agg;                                  // M x C normalised per-member scores
  if(!isE2E()){
    for(let m=0;m<M;m++) for(let c=0;c<C;c++) contrib[m][c]=wn[m]*S[m][c];   // relevance-share attribution
  }
  if(SCOREK.indexOf(algoKey)>=0){                   // score-based (wAVG, GroupIM)
    const vec = g.scoreGrid[algoKey][comboKey()] || g.scoreGrid[algoKey][eqKey()];
    for(let c=0;c<C;c++) score[c]=vec[c];
    if(isE2E()){ const att=g.att[algoKey];
      for(let c=0;c<C;c++) for(let m=0;m<M;m++) contrib[m][c]=wn[m]*att[m][c]; }
  } else {                                          // order-based (EP-FuzzDA)
    const ord = g.orderGrid[algoKey][comboKey()] || g.orderGrid[algoKey][eqKey()];
    for(let r=0;r<ord.length;r++) score[ord[r]] = (ord.length - r);
  }
  const rows=[];
  for(let c=0;c<C;c++){
    const tot = contrib.reduce((a,r)=>a+Math.max(0,r[c]),0)||1;
    rows.push({c, item:g.candidates[c], score:score[c], shares:contrib.map(r=>Math.max(0,r[c])/tot)});
  }
  rows.sort((a,b)=>b.score-a.score);
  const top=rows.slice(0,5), mx=Math.max(...top.map(r=>r.score)), mn=Math.min(...top.map(r=>r.score));
  rows.forEach((r,idx)=>{ r.rank=idx; r.bar = mx>mn ? (r.score-mn)/(mx-mn) : 1; });
  return rows;
}

function renderControls(){
  document.getElementById('algo-select').value=algoKey;
  document.getElementById('group-select').value=groupIdx;
  const a=algo(), b=document.getElementById('algo-badge');
  b.className='badge '+a.family; b.textContent=a.family;
  document.getElementById('algo-desc').textContent=a.desc;
  document.getElementById('coh-badge').textContent=`members: ${group().kind} (r=${group().cohesion})`;
  document.getElementById('method-note').textContent = isE2E()
    ? "GroupIM (deep): the influence weight is injected into the model's own attention aggregator and precomputed on a grid — NOT SAE steering. Each step is a real forward pass; equal weights = the native model."
    : "Aggregation: the influence weight is each member's importance. Weighted-average = grouprec WeightedAverageAggregator; EP-FuzzDA is the real fairness aggregator run with these member weights. (Weight-agnostic rules like least-misery are excluded — they ignore weights.)";
  document.getElementById('cand-n').textContent=group().candidates.length;
}
function updateWeightLabels(){ const wn=normWeights(); group().members.forEach((u,i)=>{const el=document.getElementById('wlab-'+i); if(el) el.textContent=Math.round(wn[i]*100)+'%';}); }
function renderUsers(){
  const g=group(), wn=normWeights();
  document.getElementById('users-container').innerHTML=g.members.map((u,i)=>`
    <div class="user-card"><div class="user-header">
      <div class="avatar" style="background:${u.bg};color:${u.color}">${u.initials}</div>
      <div><div style="font-size:13px;font-weight:500">${u.label}</div>
           <div style="font-size:11px;color:var(--text-muted)">top: ${u.history.map(title).join(' · ')||'—'}</div></div>
      <div style="margin-left:auto;font-size:12px;color:var(--text-sec)" id="wlab-${i}">${Math.round(wn[i]*100)}%</div>
    </div><div class="slider-row"><span style="font-size:11px;color:var(--text-muted)">influence</span>
      <input type="range" min="0" max="100" value="${Math.round(weights[i]*100)}" step="1"
        oninput="weights[${i}]=this.value/100;updateWeightLabels();renderRecs();renderChart()">
    </div></div>`).join('');
}
function renderRecs(){
  const g=group(), rows=computeScores().slice(0,5), ord=isOrder();
  document.getElementById('recs-container').innerHTML=rows.map((r,rank)=>{
    const dots=g.members.map((u,i)=>{const sh=r.shares[i],sc=.55+sh*1.0,op=.25+sh*.75;
      return `<div class="dot" style="background:${u.color};opacity:${op};transform:scale(${sc})"
        onmousemove="showTip(event,'${u.label}: '+Math.round(${sh}*100)+'%')" onmouseleave="hideTip()"></div>`;}).join('');
    const isPos=r.item===g.pos;
    const val = ord ? ('#'+(rank+1)) : r.score.toFixed(2);
    return `<div class="rec-item"><div class="rank-badge">${rank+1}</div>
      <div class="rec-name"><div class="title">${title(r.item)}${isPos?' <span class="pos-tag">✓</span>':''}</div>
        <div class="genre">${isPos?'consensus item':'candidate'}</div></div>
      <span class="scoreval" title="${ord?'selection rank':'group score (0–1)'}">${val}</span>
      <div class="bar-bg"><div class="bar-fill" style="width:${Math.round(r.bar*100)}%"></div></div>
      <div class="dots">${dots}</div></div>`;
  }).join('');
}
function renderChart(){
  const g=group(), rows=computeScores().slice(0,5);
  const totals=g.members.map((_,i)=>rows.reduce((a,r)=>a+r.shares[i],0));
  const tot=totals.reduce((a,b)=>a+b,0)||1, data=totals.map(t=>+(100*t/tot).toFixed(1));
  const ds=g.members.map((u,i)=>({label:u.label,data:[data[i]],backgroundColor:u.color,borderWidth:0}));
  if(chart){ chart.data.datasets=ds; chart.update('none'); return; }
  chart=new Chart(document.getElementById('contrib-chart'),{type:'bar',
    data:{labels:['top-5 contribution'],datasets:ds},
    options:{indexAxis:'y',responsive:true,maintainAspectRatio:false,
      scales:{x:{stacked:true,max:100,ticks:{callback:v=>v+'%',color:'#888'},grid:{display:false}},y:{stacked:true,grid:{display:false},ticks:{display:false}}},
      plugins:{legend:{position:'bottom',labels:{boxWidth:10,font:{size:11}}},tooltip:{callbacks:{label:c=>c.dataset.label+': '+c.raw+'%'}}}}});
}
function setAttrView(v){ attrView=v; document.querySelectorAll('#attr-tabs .tab-btn').forEach(b=>b.classList.toggle('active',b.dataset.v===v)); renderAttr(); }
function renderAttr(){
  const g=group(), el=document.getElementById('attr-detail'), note=document.getElementById('attr-note');
  note.textContent='';
  if(attrView==='history'){
    el.innerHTML=g.members.map(u=>`<b>${u.label}:</b> <span class="mono">${u.history.map(title).join(', ')||'—'}</span>`).join('<br>');
    note.textContent='Each member\'s top-3 films by rating (ties broken by item id), from the real ml-100k ratings.';
  } else if(attrView==='received'){
    el.innerHTML=g.members.map((u,i)=>{
      const order=[...g.agg[i].keys()].sort((a,b)=>g.agg[i][b]-g.agg[i][a]);
      return `<b>${u.label}:</b> <span class="mono">${order.slice(0,3).map(c=>title(g.candidates[c])).join(', ')}</span>`;
    }).join('<br>');
    note.textContent='Each member\'s own top-3 candidates from the EASE base recommender, before any group merging.';
  } else {
    if(isE2E()){
      el.innerHTML=`<span style="color:var(--text-muted)">Latent concepts are an SAE over the recommender's item embeddings; they explain members, not the deep model's steering. Switch to an [AGG] algorithm to inspect them.</span>`;
    } else {
      el.innerHTML=g.members.map(u=>{
        const f=u.sae.map(s=>`<b style="color:var(--agg)">${s.label}</b> <span class="mono">[${s.items.map(title).join(', ')}]</span>`).join('<br>&nbsp;&nbsp;');
        return `<b>${u.label}:</b><br>&nbsp;&nbsp;${f}`;
      }).join('<br>');
      note.textContent='Concepts a member triggers (top-3 by activation over their history), from a Top-K SAE over item embeddings, labelled by the genre of each concept\'s top items. The films listed are the concept\'s exemplars, so they may differ from the member\'s own history.';
    }
  }
}
function renderLegend(){
  document.getElementById('legend').innerHTML=group().members.map(u=>
    `<div class="legend-item"><div class="legend-dot" style="background:${u.color}"></div>${u.label}</div>`).join('');
}
function showTip(e,t){ tip.textContent=t; tip.style.opacity=1; const w=tip.offsetWidth;
  let x=e.clientX+12; if(x+w>window.innerWidth-8) x=e.clientX-w-12;
  tip.style.left=Math.max(4,x)+'px'; tip.style.top=(e.clientY+12)+'px'; }
function hideTip(){ tip.style.opacity=0; }
function renderAll(){ renderControls(); renderUsers(); renderRecs(); renderChart(); renderAttr(); renderLegend(); }
initControls(); resetWeights();
</script>
</body>
</html>
"""


def main() -> None:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--out", default="docs/group_rec_explorer.html")
    a = p.parse_args()
    build(Path(a.out))


if __name__ == "__main__":
    main()
